chain.name=audio.detect.chain
chain.version=v1
chain.execute.mode=SYNC
chain.exception.policy=BREAK

execute.handlers=bean&name:detect.param.validate.handler,bean&name:detect.audio.fetch.handler,bean&name:detect.asr.handler,bean&name:detect.text.keyword.handler,bean&name:detect.mock.text.model.handler
finally.handler=bean&name:detect.finally.handler
