chain.name=test.detect.chain
chain.version=v1
chain.execute.mode=SYNC
chain.exception.policy=BREAK

execute.handlers=bean&name:test.start.handler,bean&name:test.middle.handler
finally.handler=bean&name:test.finally.handler
